/*
ALTER TABLE Valdivia.PERSONA
ADD COLUMN nivel_de_estudio INT;
*/
CREATE TABLE IF NOT EXISTS CATEGORIES (
	cat_id INT NOT NULL AUTO_INCREMENT,
	categoria varchar(50) NOT NULL,
    PRIMARY KEY (cat_id));

ALTER TABLE Valdivia.LUGAR_DE_INTERES
DROP COLUMN cat_id;

ALTER TABLE Valdivia.LUGAR_DE_INTERES
ADD COLUMN cat_id INT AFTER descripcion;

ALTER TABLE Valdivia.LUGAR_DE_INTERES
ADD FOREIGN KEY fk_cat(cat_id)
REFERENCES CATEGORIES(cat_id) 
ON DELETE NO ACTION
ON UPDATE CASCADE;

ALTER TABLE Valdivia.LUGAR_DE_INTERES
CHANGE COLUMN latitud latitud FLOAT(20,6) NOT NULL,
CHANGE COLUMN longitud longitud FLOAT(20,6) NOT NULL;
